version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skill-graph-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - skill-graph-network
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=skill_graph
      - DB_USERNAME=skill_graph_user
      - DB_PASSWORD=skill_graph_password
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8.0
    container_name: skill-graph-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: skill_graph
      MYSQL_USER: skill_graph_user
      MYSQL_PASSWORD: skill_graph_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - skill-graph-network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: skill-graph-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    networks:
      - skill-graph-network
    depends_on:
      - mysql

  node:
    image: node:18-alpine
    container_name: skill-graph-node
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - skill-graph-network
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  mysql-data:
    driver: local

networks:
  skill-graph-network:
    driver: bridge 