<div class="{{ $attributes['class'] }}">
    <input class="radio" @if(isset($attributes['disabled'])) disabled @endif @if(isset($attributes['wire:change'])) wire:change="{{ $attributes['wire:change'] }}" @endif @if(isset($attributes['wire:model'])) wire:model="{{ $attributes['wire:model'] }}" @endif @if(isset($attributes['wire:model.defer'])) wire:model.defer="{{ $attributes['wire:model.defer'] }}" @endif type="radio" id="{{ $attributes['id'] }}" name="{{ $attributes['name'] }}" value="1"{{ $attributes['value'] == 1 ? ' checked' : '' }} @if(isset($attributes['@change-yes']))) @change="{{ $attributes['@change-yes'] }}" @endif > <label class="{{$attributes['labelclass']}} me-2" for="">{{ __('Yes') }}</label>
    <input class="radio" @if(isset($attributes['disabled'])) disabled @endif @if(isset($attributes['wire:change'])) wire:change="{{ $attributes['wire:change'] }}" @endif @if(isset($attributes['wire:model'])) wire:model="{{ $attributes['wire:model'] }}" @endif @if(isset($attributes['wire:model.defer'])) wire:model.defer="{{ $attributes['wire:model.defer'] }}" @endif type="radio" id="{{ $attributes['id'] }}-no" name="{{ $attributes['name'] }}" value="0"{{ $attributes['value'] == 1 ? '' : ' checked' }} @if(isset($attributes['@change-no'])) @change="{{ $attributes['@change-no'] }}" @endif> <label class="{{$attributes['labelclass']}} me-2" for="">{{ __('No') }}</label>

    @if(isset($attributes['na']) && $attributes['na'])
        <input class="radio" @if(isset($attributes['wire:model'])) wire:model="{{ $attributes['wire:model'] }}" @endif @if(isset($attributes['wire:model.defer'])) wire:model.defer="{{ $attributes['wire:model.defer'] }}" @endif type="radio" id="{{ $attributes['id'] }}-na" name="{{ $attributes['name'] }}" value="n/a"{{ $attributes['value'] == '' ? ' checked' : '' }} @if(isset($attributes['@change-na'])) @change="{{ $attributes['@change-na'] }}" @endif> <label class="{{$attributes['labelclass']}} me-2" for="">N/A</label>
    @endif

</div>
